from __future__ import annotations

from app.schemas.recommendation import EmploymentDirectionPayload


EMPLOYMENT_DIRECTION_BASELINES: list[EmploymentDirectionPayload] = [
    EmploymentDirectionPayload(
        name="软件平台工程",
        category="技术研发类",
        alias_names_json=["软件研发", "平台开发", "后端开发"],
        description="面向软件系统、平台架构、企业数字化与应用研发岗位。",
        common_job_types_json=["后端开发", "平台研发", "系统研发"],
        common_industries_json=["互联网", "企业信息化", "软件服务"],
        prefers_postgraduate=False,
        requires_certificate=False,
        requires_long_cycle=False,
        supports_art=False,
        risk_note="技术迭代快，需要持续学习和工程实践。",
        source_note="系统基线初始化生成",
        is_active=True,
    ),
    EmploymentDirectionPayload(
        name="数据智能分析",
        category="数字化与新职业类",
        alias_names_json=["数据分析", "算法分析", "商业分析"],
        description="面向数据分析、算法支持、智能决策和数据产品岗位。",
        common_job_types_json=["数据分析师", "算法工程师", "BI分析"],
        common_industries_json=["人工智能", "互联网", "企业数字化"],
        prefers_postgraduate=False,
        requires_certificate=False,
        requires_long_cycle=False,
        supports_art=False,
        risk_note="岗位分化快，部分细分方向对数理和编程要求较高。",
        source_note="系统基线初始化生成",
        is_active=True,
    ),
    EmploymentDirectionPayload(
        name="智能制造与自动化",
        category="制造工程类",
        alias_names_json=["智能制造", "自动化工程", "机电制造"],
        description="面向制造系统、自动化产线、机电设备与工业控制岗位。",
        common_job_types_json=["自动化工程师", "工艺工程师", "设备工程师"],
        common_industries_json=["高端制造", "汽车", "工业自动化"],
        prefers_postgraduate=False,
        requires_certificate=False,
        requires_long_cycle=False,
        supports_art=False,
        risk_note="实践和现场经验重要，部分岗位存在倒班或驻场情形。",
        source_note="系统基线初始化生成",
        is_active=True,
    ),
    EmploymentDirectionPayload(
        name="医疗健康服务",
        category="医药健康类",
        alias_names_json=["医疗健康", "临床服务", "药学服务"],
        description="面向医疗、护理、药学、康复和健康管理岗位。",
        common_job_types_json=["临床岗位", "护理岗位", "药学岗位"],
        common_industries_json=["医院", "医药", "康复健康"],
        prefers_postgraduate=True,
        requires_certificate=True,
        requires_long_cycle=True,
        supports_art=False,
        risk_note="职业资格和培养周期要求高，岗位准入严格。",
        source_note="系统基线初始化生成",
        is_active=True,
    ),
    EmploymentDirectionPayload(
        name="教育教学与教研",
        category="教育教学类",
        alias_names_json=["教育教学", "教研发展", "教师岗位"],
        description="面向中小学、学前、职业教育与教育研究岗位。",
        common_job_types_json=["教师", "教研员", "教育产品"],
        common_industries_json=["基础教育", "职业教育", "教育服务"],
        prefers_postgraduate=False,
        requires_certificate=True,
        requires_long_cycle=False,
        supports_art=True,
        risk_note="多数正式教学岗位需要教师资格证和持续教研能力。",
        source_note="系统基线初始化生成",
        is_active=True,
    ),
    EmploymentDirectionPayload(
        name="财会金融与审计",
        category="财经管理类",
        alias_names_json=["财会金融", "审计风控", "金融管理"],
        description="面向会计、审计、税务、金融分析与风控岗位。",
        common_job_types_json=["会计", "审计", "金融分析"],
        common_industries_json=["金融", "企业管理", "会计服务"],
        prefers_postgraduate=False,
        requires_certificate=True,
        requires_long_cycle=False,
        supports_art=False,
        risk_note="资格证和实务经验会显著影响竞争力。",
        source_note="系统基线初始化生成",
        is_active=True,
    ),
    EmploymentDirectionPayload(
        name="法政与公共治理",
        category="法政公共服务类",
        alias_names_json=["法政公共服务", "公共治理", "政法服务"],
        description="面向法务、公共管理、行政服务、基层治理与考公相关岗位。",
        common_job_types_json=["法务", "公共管理", "行政管理"],
        common_industries_json=["政府事业单位", "公共服务", "法律服务"],
        prefers_postgraduate=False,
        requires_certificate=True,
        requires_long_cycle=False,
        supports_art=False,
        risk_note="部分岗位受编制、考试与资格要求影响较大。",
        source_note="系统基线初始化生成",
        is_active=True,
    ),
    EmploymentDirectionPayload(
        name="传媒内容与视觉设计",
        category="传媒设计类",
        alias_names_json=["传媒设计", "内容创意", "视觉传播"],
        description="面向媒体内容、品牌传播、视觉设计和数字创意岗位。",
        common_job_types_json=["内容策划", "视觉设计", "新媒体运营"],
        common_industries_json=["传媒", "广告", "数字内容"],
        prefers_postgraduate=False,
        requires_certificate=False,
        requires_long_cycle=False,
        supports_art=True,
        risk_note="作品集和项目经验影响很大，岗位波动也相对明显。",
        source_note="系统基线初始化生成",
        is_active=True,
    ),
    EmploymentDirectionPayload(
        name="供应链与物流运营",
        category="服务运营类",
        alias_names_json=["物流运营", "供应链管理", "交通运输服务"],
        description="面向物流、港航、运输组织、仓储与供应链管理岗位。",
        common_job_types_json=["物流运营", "供应链专员", "港航管理"],
        common_industries_json=["物流", "港口航运", "供应链服务"],
        prefers_postgraduate=False,
        requires_certificate=False,
        requires_long_cycle=False,
        supports_art=False,
        risk_note="岗位区域性明显，一线运营和现场协调能力要求高。",
        source_note="系统基线初始化生成",
        is_active=True,
    ),
    EmploymentDirectionPayload(
        name="建筑工程与项目管理",
        category="制造工程类",
        alias_names_json=["建筑工程", "土建项目", "工程管理"],
        description="面向土木、建筑、造价、施工组织与工程项目管理岗位。",
        common_job_types_json=["施工管理", "造价管理", "项目管理"],
        common_industries_json=["建筑工程", "基础设施", "房地产服务"],
        prefers_postgraduate=False,
        requires_certificate=True,
        requires_long_cycle=False,
        supports_art=False,
        risk_note="执业资格和现场经验对职业发展影响明显。",
        source_note="系统基线初始化生成",
        is_active=True,
    ),
    EmploymentDirectionPayload(
        name="农业科技与食品质量",
        category="农林生态类",
        alias_names_json=["农业食品", "农林科技", "食品质量"],
        description="面向农业科技、园林生态、食品检测与农产品加工岗位。",
        common_job_types_json=["农业技术", "食品检测", "园林技术"],
        common_industries_json=["农业科技", "食品加工", "生态服务"],
        prefers_postgraduate=False,
        requires_certificate=False,
        requires_long_cycle=False,
        supports_art=False,
        risk_note="岗位受区域和产业分布影响较大，实践场景重要。",
        source_note="系统基线初始化生成",
        is_active=True,
    ),
    EmploymentDirectionPayload(
        name="国际商务与外语服务",
        category="财经管理类",
        alias_names_json=["国际商务", "外语服务", "跨境业务"],
        description="面向外语应用、国际商务、跨境电商与国际服务岗位。",
        common_job_types_json=["商务助理", "跨境运营", "外语服务"],
        common_industries_json=["国际贸易", "跨境电商", "商务服务"],
        prefers_postgraduate=False,
        requires_certificate=False,
        requires_long_cycle=False,
        supports_art=False,
        risk_note="语言能力和实际业务场景经验对竞争力影响很大。",
        source_note="系统基线初始化生成",
        is_active=True,
    ),
    EmploymentDirectionPayload(
        name="艺术创作与演艺",
        category="艺术体育类",
        alias_names_json=["艺术创作", "演艺传播", "舞台艺术"],
        description="面向美术设计、舞台表演、音乐创作与艺术传播岗位。",
        common_job_types_json=["艺术设计", "表演创作", "舞台传播"],
        common_industries_json=["文化艺术", "演艺传媒", "创意服务"],
        prefers_postgraduate=False,
        requires_certificate=False,
        requires_long_cycle=False,
        supports_art=True,
        risk_note="作品、项目和平台资源对发展影响明显。",
        source_note="系统基线初始化生成",
        is_active=True,
    ),
    EmploymentDirectionPayload(
        name="体育训练与健康管理",
        category="艺术体育类",
        alias_names_json=["体育训练", "运动健康", "体育康复"],
        description="面向体育训练、运动指导、体能管理与健康服务岗位。",
        common_job_types_json=["教练", "运动指导", "健康管理"],
        common_industries_json=["体育教育", "健身健康", "运动服务"],
        prefers_postgraduate=False,
        requires_certificate=True,
        requires_long_cycle=False,
        supports_art=True,
        risk_note="技能证书、赛事经验和实践能力影响较大。",
        source_note="系统基线初始化生成",
        is_active=True,
    ),
]


EMPLOYMENT_MAPPING_RULES: list[dict[str, object]] = [
    {
        "direction": "软件平台工程",
        "strength": "core",
        "major_keywords": ["软件工程", "计算机科学", "信息安全", "网络工程", "物联网工程", "数字媒体技术"],
        "category_keywords": ["计算机类", "电子与信息大类"],
        "supports_art": False,
    },
    {
        "direction": "数据智能分析",
        "strength": "core",
        "major_keywords": ["人工智能", "数据科学", "大数据", "统计学", "智能科学", "机器人工程"],
        "category_keywords": ["工学", "理学"],
        "supports_art": False,
    },
    {
        "direction": "智能制造与自动化",
        "strength": "core",
        "major_keywords": ["自动化", "机械", "机电", "电气", "车辆工程", "材料成型", "工业机器人", "新能源装备"],
        "category_keywords": ["装备制造大类", "能源动力与材料大类"],
        "supports_art": False,
    },
    {
        "direction": "医疗健康服务",
        "strength": "core",
        "major_keywords": ["医学", "护理", "药学", "口腔", "康复", "检验", "中医", "临床"],
        "category_keywords": ["医学", "医药卫生大类"],
        "requires_certificate": True,
        "requires_postgraduate": True,
        "supports_art": False,
    },
    {
        "direction": "教育教学与教研",
        "strength": "core",
        "major_keywords": ["教育", "师范", "学前", "小学", "特殊教育", "体育教育"],
        "category_keywords": ["教育学", "教育与体育大类"],
        "requires_certificate": True,
        "supports_art": True,
    },
    {
        "direction": "财会金融与审计",
        "strength": "core",
        "major_keywords": ["会计", "审计", "金融", "税收", "保险", "财政", "经济学", "财务"],
        "category_keywords": ["经济学", "财经商贸大类", "管理学"],
        "requires_certificate": True,
        "supports_art": False,
    },
    {
        "direction": "法政与公共治理",
        "strength": "core",
        "major_keywords": ["法学", "政治", "行政管理", "社会工作", "公安", "司法", "思想政治"],
        "category_keywords": ["法学", "公安与司法大类", "公共管理与服务大类"],
        "requires_certificate": True,
        "supports_art": False,
    },
    {
        "direction": "传媒内容与视觉设计",
        "strength": "core",
        "major_keywords": ["新闻", "传播", "广告", "视觉传达", "数字媒体艺术", "动画", "广播电视", "编导", "设计"],
        "category_keywords": ["艺术学", "文化艺术大类", "新闻传播大类"],
        "supports_art": True,
        "supported_student_types_json": ["art"],
    },
    {
        "direction": "供应链与物流运营",
        "strength": "core",
        "major_keywords": ["物流", "供应链", "港口", "航海", "轮机", "交通运输", "邮政", "铁道", "航空服务"],
        "category_keywords": ["交通运输大类", "服务运营类"],
        "supports_art": False,
    },
    {
        "direction": "建筑工程与项目管理",
        "strength": "core",
        "major_keywords": ["土木", "建筑", "工程造价", "城乡规划", "风景园林", "水利", "测绘"],
        "category_keywords": ["土木建筑大类", "水利大类", "资源环境与安全大类"],
        "requires_certificate": True,
        "supports_art": False,
    },
    {
        "direction": "农业科技与食品质量",
        "strength": "core",
        "major_keywords": ["农业", "园艺", "林学", "动物", "食品", "农学", "植物", "畜牧", "园林"],
        "category_keywords": ["农学", "农林牧渔大类", "食品药品与粮食大类"],
        "supports_art": False,
    },
    {
        "direction": "国际商务与外语服务",
        "strength": "core",
        "major_keywords": ["英语", "商务英语", "翻译", "国际经济与贸易", "日语", "俄语", "法语", "德语", "韩语"],
        "category_keywords": ["文学"],
        "supports_art": False,
    },
    {
        "direction": "艺术创作与演艺",
        "strength": "core",
        "major_keywords": ["美术", "绘画", "表演", "舞蹈", "音乐", "戏剧", "影视", "播音", "服装设计"],
        "category_keywords": ["艺术学", "文化艺术大类"],
        "supports_art": True,
        "supported_student_types_json": ["art"],
    },
    {
        "direction": "体育训练与健康管理",
        "strength": "core",
        "major_keywords": ["体育", "运动训练", "社会体育", "休闲体育", "体能", "运动康复"],
        "category_keywords": ["教育与体育大类"],
        "supports_art": True,
        "supported_student_types_json": ["sports"],
        "requires_certificate": True,
    },
]
